### ISSUE TITLE
发现了一个问题

### ISSUE THREAD

**Issue by Yexinglong** [bb-coder/BHBDrawBoarderDemo#3]
当CAShapeLayer  添加了非常多个的时候，性能会被降低，内存和CPU是没有任何改变，但GPU逐渐上升，最后造成卡顿卡顿！如果使用了CAShapeLayer 橡皮擦这个功能无法真正的实现擦除！你有更好的思路么？

**Comment by Yexinglong** [comment]
你可以尝试将画笔增粗，然后换着颜色去涂满整个屏幕，多涂几次就会感觉到一些卡顿了！

**Comment by bb-coder** [comment]
好的，我在寻找解决办法，之后回复您，多谢支持😁

**Comment by bb-coder** [comment]
您好，感谢您的建议，性能上的问题我这里不是特别明显，画笔改为100，instrument上测试的GPU数据如图：
<img width="1261" alt="screen shot 2016-04-06 at 6 29 35 pm" src="https://cloud.githubusercontent.com/assets/7802862/14313691/94a28a6c-fc25-11e5-9e5e-507370651a55.png">

橡皮擦可以参考[这里](https://github.com/bb-coder/BHBDrawBoarderDemo/issues/1)

**Comment by bb-coder** [comment]
不好意思，刚才我用1000width的画笔又试了一下，GPU占用确实会在频繁（20年单身手速画）的绘制时非常的高（有时会到100），但是随着绘制频率的降低情况会有所改善，其实优化的思路就是GPU和CPU之间的权衡，目前我没有想到一个完美的GPU和CPU都很低并且内存不高的解决方案。

**Comment by Yexinglong** [comment]
哈哈哈哈哈~你好有意思啊！

**Comment by Yexinglong** [comment]
嘿~哥们，我做出一个比较完美的画板了！GPU与CPU之间都共用，思路就是用CAShapeLayer  来画当前的线，画完后removeFromSuperlayer，NSUndoManager 来保存当前的位图 虽说放大5倍以上会出现锯齿，但是无所谓啦！我就不给他放大五倍就行啦！然后橡皮擦可以实现真正的擦除了！话说，你还需要女朋友吗？给你介绍介绍

**Comment by bb-coder** [comment]
牛啊，你有Demo吗，可以的话邮箱发给我研究研究bbcoderios@gmail.com，正好我把这个Demo完善一下。最近工作比较忙，一直也没有去认真思考这个Demo。  
你资源还不少啊，哈哈，女朋友还是留给别人吧，我有女朋友了😄。
